version: "3.7"
services:

## --------------------------- POKER --------------------------- ##
  poker:
    image: ofcedsoncosta/poker-web:latest
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
    volumes:
      - poker:/app/data
    networks:
      - ecsistem
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

  sync-server:
    image: ofcedsoncosta/poker-sync-server:latest
    volumes:
      - poker:/app/data
    networks:
      - ecsistem
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1024M

## --------------------------- POKER --------------------------- ##

volumes:
  poker:
    external: true
    name: poker

networks:
  ecsistem:
    external: true
    name: ecsistem
